# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/DrayChou/"
  #weibo: "#"
  rss: "http://feeds.feedburner.com/WesHome"
  #zhihu: "#"
  #mail: "#"
  #facebook: "#"
  #douban: "#"
  #google: "#"
  twitter: "http://twitter.com/_0dc/"
  #linkedin: "#"
  #QQ: "#"
  #微信: "Wechat"
  #PayPal: "#"
  #StackOverflow: "#"
  #Instagram: "#"
  #Flickr: "#"

# "5": show images form bg-1.jpg to bg-5.jpg in `/yelee/source/background/`
# "5": 显示`/yelee/source/background/`文件夹中 bg-1.jpg 到 bg-5.jpg 这5张图片
# "0": white-gray background | 淳朴灰白背景
background_image: 1

# Content
excerpt_link: 大航海 #修改more>>的文字

fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
baidu_analytics: false
favicon: /favicon.ico

#你的头像url
avatar: http://s.gravatar.com/avatar/00ced3a6cdfd0398fabe0717147a6a32?s=200
#是否开启分享
share: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key（http://duoshuo-key.duoshuo.com/）
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  方片子的博客: http://www.fangshanzi.com/
  Locyoo Manor|部落格: http://locyoo.com/blog/
  方片快报: http://fpnews.cn/
  黄书快报: http://hskb.me/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…
